### PR TITLE
Add dune-lint job to GitHub Actions workflow

### PR DESCRIPTION
**Pull request by smorimoto**
As the title says. And errors related to depext have been fixed on the latest master.

### CODE REVIEW

**Comment by shonfeder** [comment]
OMG! What a lovely CI present to find at the end of the work day :smile: .

Many thanks, @smorimoto!

Out of curiosity, would you always recommend running each of these checks as their own job, or is it just as good to just enable them all in one build/test job?

**Comment by smorimoto** [comment]
Haha, thanks for your kind words :) Hmm, there is no problem to do all the checks in a single job. There is no major difference between them, so I often run them as separate jobs just for the sake of clarity. (If there is a difference, the deep dependencies of the tools installed by lint-fmt or lint-doc can affect the dependencies version that listed in the opam file, and I think there is a very rare case where something could happen. But I'm not sure.)

**Comment by shonfeder** [comment]
That makes sense! This way I can see which check failed without even having to open up the results. That does help with clarity.

Thanks again! I think my OCaml GitHub CI  knowledge has doubled this week, thanks to your interventions :star2:

**Comment by smorimoto** [comment]
Anytime!

**Pull request merged**
